site_name: Protected MkDocs

nav:
  - Home: index.md
  - Authentication: auth.html

# extra_css:
#   - styles.css

extra_javascript:
  - auth.js
  - restrict.js # New script to check authentication on every page
